language: cpp
compiler:
  - gcc
  - clang
script:
   mkdir build &&
   mkdir build/Debug && 
   mkdir build/Release &&
   pushd build/Debug && 
   cmake -DCMAKE_BUILD_TYPE=Debug ../.. && 
   make &&
   ctest -C Debug &&
   popd